// <auto-generated />
using System;
using JMP.Enterprises.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JMP.Enterprises.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909090653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JMP.Enterprises.Api.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultDailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultMonthlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PropertyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PropertyId");

                    b.HasIndex("PropertyCode")
                        .IsUnique();

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            CreatedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDailyRate = 0m,
                            DefaultMonthlyRate = 0m,
                            IsActive = true,
                            PropertyCode = "LILY",
                            PropertyName = "Lily",
                            Status = "Available"
                        },
                        new
                        {
                            PropertyId = 2,
                            CreatedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDailyRate = 0m,
                            DefaultMonthlyRate = 0m,
                            IsActive = true,
                            PropertyCode = "LALA",
                            PropertyName = "Lala",
                            Status = "Available"
                        },
                        new
                        {
                            PropertyId = 3,
                            CreatedDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDailyRate = 0m,
                            DefaultMonthlyRate = 0m,
                            IsActive = true,
                            PropertyCode = "PAMAE",
                            PropertyName = "Pamae",
                            Status = "Available"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
